### ISSUE TITLE
useFetch

### ISSUE THREAD

**Issue by ergenekonyigit** [rehooks/ideas#35]
hi, I made a small hook lib 🙂
https://github.com/ergenekonyigit/useFetch
@jamiebuilds

**Comment by gus3inov** [comment]
pretty nice

**Comment by ganapativs** [comment]
Configurable datatype?

**Comment by styfle** [comment]
I think this will cache the data based on the URL? That means it should only be used for GET requests.

**Comment by prichodko** [comment]
I think it should at least mimic Fetch API, e. g. accept URL and options object.

**Comment by jxom** [comment]
This hook is kind of implicitly achieved in https://github.com/rehooks/ideas/issues/24. I think it would be nicer if we left the 'fetcher' implementation up to the user. The reason why I say this is because we might want to use the kind of behaviour this hook has for different kinds of things like an SDK, a different HTTP client like Axios, or even a promise in general. Let me know your thoughts!
